export const INITIALIZE_ORDER = "INITIALIZE_ORDER"

export const MAKE_ORDER_REQUEST = "MAKE_ORDER_REQUEST"
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS"
export const MAKE_ORDER_FAIL = "MAKE_ORDER_FAIL"

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAIL = "GET_ORDER_FAIL"

export const SET_DELIVERED_REQUEST = "SET_DELIVERED_REQUEST"
export const SET_DELIVERED_SUCCESS = "SET_DELIVERED_SUCCESS"
export const SET_DELIVERED_FAIL = "SET_DELIVERED_FAIL"
export const CLEAR_SET_DELIVERED = "CLEAR_SET_DELIVERED"

export const GET_ALLORDER_REQUEST = "GET_ALLORDER_REQUEST"
export const GET_ALLORDER_SUCCESS = "GET_ALLORDER_SUCCESS"
export const GET_ALLORDER_FAIL = "GET_ALLORDER_FAIL"

export const GET_ORDERDETAILS_REQUEST = "GET_ORDERDETAILS_REQUEST"
export const GET_ORDERDETAILS_SUCCESS = "GET_ORDERDETAILS_SUCCESS"
export const GET_ORDERDETAILS_FAIL = "GET_ORDERDETAILS_FAIL"


export const DELETE_ORDER = "DELETE_ORDER"
export const ADMIN_DELETE_ORDER = "ADMIN_DELETE_ORDER"


