export const LIST_PRODUCTS_REQUEST = 'LIST_PRODUCTS_REQUEST';
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS';
export const LIST_PRODUCTS_FAIL = 'LIST_PRODUCTS_FAIL';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL';


export const LIST_CATEGORY_REQUEST = 'LIST_CATEGORY_REQUEST';
export const LIST_CATEGORY_SUCCESS = 'LIST_CATEGORY_SUCCESS';
export const LIST_CATEGORY_FAIL = 'LIST_CATEGORY_FAIL';

export const ADD_PRODUCTS_REQUEST = 'ADD_PRODUCTS_REQUEST';
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCTS_FAIL = 'ADD_PRODUCTS_FAIL';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CLEAR_ADD_PRODUCT = 'CLEAR_ADD_PRODUCT';

export const ADD_SALE_REQUEST = 'ADD_SALE_REQUEST';
export const ADD_SALE_SUCCESS = 'ADD_SALE_SUCCESS';
export const ADD_SALE_FAIL = 'ADD_SALE_FAIL';
export const CLEAR_ADD_SALE = 'CLEAR_ADD_SALE';

export const DELETE_SALE_REQUEST = 'DELETE_SALE_REQUEST';
export const DELETE_SALE_SUCCESS = 'DELETE_SALE_SUCCESS';
export const DELETE_SALE_FAIL = 'DELETE_SALE_FAIL';
export const CLEAR_DELETE_SALE = 'CLEAR_DELETE_SALE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_COMMENT = 'ADD_COMMENT';
export const CLEAR_ADD_COMMENT = 'CLEAR_ADD_COMMENT';



export const UPDATE_PRODUCTS_REQUEST = 'UPDATE_PRODUCTS_REQUEST';
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAIL = 'UPDATE_PRODUCTS_FAIL';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';

export const GET_FILTERED_PRODUCTS_REQUEST = 'GET_FILTERED_PRODUCTS_REQUEST';
export const GET_FILTERED_PRODUCTS_SUCCESS = 'GET_FILTERED_PRODUCTS_SUCCESS';
export const GET_FILTERED_PRODUCTS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';
export const CLEAR_FILTER_PRODUCTS= 'CLEAR_FILTER_PRODUCTS';

export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';
export const CLEAR_INFO = 'CLEAR_INFO';

export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_FAIL = 'GET_SEARCH_FAIL';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';



export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';

