export const ADD_SHIPPING_REQUIST = 'ADD_SHIPPING_REQUIST';
export const ADD_SHIPPING_SUCCESS = 'ADD_SHIPPING_SUCCESS';
export const ADD_SHIPPING_FAIL = 'ADD_SHIPPING_FAIL';
export const CLEAR_ADD_SHIPPING = 'CLEAR_ADD_SHIPPING';


export const GET_SHIPPING_REQUIST = 'GET_SHIPPING_REQUIST';
export const GET_SHIPPING_SUCCESS = 'GET_SHIPPING_SUCCESS';
export const GET_SHIPPING_FAIL = 'GET_SHIPPING_FAIL';



export const DELETE_SHIPPING_REQUIST = 'DELETE_SHIPPING_REQUIST';
export const DELETE_SHIPPING_SUCCESS = 'DELETE_SHIPPING_SUCCESS';
export const DELETE_SHIPPING_FAIL = 'DELETE_SHIPPING_FAIL';



export const MAKE_SHIPPING_DEFAULT_REQUIST = 'MAKE_SHIPPING_DEFAULT_REQUIST';
export const MAKE_SHIPPING_DEFAULT_SUCCESS = 'MAKE_SHIPPING_DEFAULT_SUCCESS';
export const MAKE_SHIPPING_DEFAULT_FAIL = 'MAKE_SHIPPING_DEFAULT_FAIL';


